python: 2.7

sudo: required

matrix:
  include:
    - os: linux
      python: 3.4
      env: TOX_ENV=quality
    - os: osx
      language: generic
      env: TOX_ENV=py27
    - os: osx
      language: generic
      env: TOX_ENV=py36
    - os: linux
      language: python
      env: TOX_ENV=py27
    - os: linux
      language: python
      env: TOX_ENV=py33
    - os: linux
      language: python
      env: TOX_ENV=py34
    - os: linux
      language: python
      python: 3.5
      env: TOX_ENV=py35
    - os: linux
      language: python
      python: 3.6
      env: TOX_ENV=py36
  exclude:
    - python: 2.7 # hack to exclude default no-env travis job

install:
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew unlink python
      brew unlink python3
      if [[ TOX_ENV == py2* ]]; then
        brew install python
      else
        brew install python3
      fi
    fi
  - |
    if [[ TOX_ENV == py2* ]]; then
      pip install -U pip setuptools tox
    else
      pip3 install -U pip setuptools tox
    fi

script:
    - tox -e $TOX_ENV

after_success:
  - |
    if [[ "$TOX_ENV" == "py27" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      coveralls;
    fi;
